=== TheGalekxy/HumberProjects/XMLAssignment2-master/xml/tickets.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tickets">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ticket" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="userid" type="xs:int" />
                            <xs:element name="ticketid" type="xs:int" />
                            <xs:element name="datetimeissued" type="xs:dateTime" />
                            <xs:element name="subject" type="xs:string" />
                            <xs:element name="status" type="xs:string" />
                            <xs:element name="messages">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="message" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="datetime" type="xs:dateTime" />
                                                    <xs:element name="content" type="xs:string" />
                                                    <xs:element name="senderId" type="xs:int" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TheGalekxy/HumberProjects/XMLAssignment2-master/xml/tickets.xml
<?xml version="1.0" encoding="utf-8"?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tickets.xsd">
  <ticket>
    <userid>1</userid>
    <ticketid>1</ticketid>
    <datetimeissued>2021-02-06T09:30:14</datetimeissued>
    <subject>Computer Stopped Working</subject>
    <status>Open</status>
    <messages>
      <message>
        <datetime>2021-02-06T09:34:25</datetime>
        <content>My Computer Got a Blue Screen of death.</content>
        <senderId>1</senderId>
      </message>
      <message>
        <datetime>2021-02-06T09:34:25</datetime>
        <content>Okay, we can help you with that.</content>
        <senderId>2</senderId>
      </message>
    </messages>
  </ticket>
  <ticket>
    <userid>2</userid>
    <ticketid>2</ticketid>
    <datetimeissued>2021-02-06T09:30:14</datetimeissued>
    <subject>Laptop Died</subject>
    <status>Open</status>
    <messages>
      <message>
        <datetime>2021-02-06T09:34:25</datetime>
        <content>My computer got really hot and then shut down and won't turn back on.</content>
        <senderId>2</senderId>
      </message>
    </messages>
  </ticket>
</tickets>
